### ISSUE TITLE
Database ToDo

### ISSUE THREAD

**Issue by GaalexxC** [GaalexxC/IPS-4.3-BitTracker#2]
Couple things still need attention

- On update CURRENT_TIMESTAMP insertion for bitracker_scrape last_update
- Default extensions insert

**Comment by AmsalKhan** [comment]
Just want to say thanks for working on this out, there are really many people who looking forward for this through anonymous state also!

Thank You

**Comment by GaalexxC** [comment]
Fixed ENUM issues in schema.xml
Fixed default ctypes issue in schema.xml
