### ISSUE TITLE
SSL Error Devcu Website

### ISSUE THREAD

**Issue by STX2k** [GaalexxC/IPS-4.3-BitTracker#6]
Hey GaalexxC, 

i get an SSL ERROR if i try to open https://www.devcu.com

And another Question. Is the developement still active? 

Greets STX

**Comment by GaalexxC** [comment]
Yes I have renewed the SSL, apologies for the inconvenience.

**Comment by STX2k** [comment]
Nice. 👌 And ist developement still active? I really hope so. 👍

**Comment by GaalexxC** [comment]
Yes was away for a month and am back. Will be hitting this full bore this week and testing at my site by next week. Hope to have a release shortly. Apologies for the delay but it is Summer and I do enjoy my time off.

**Comment by STX2k** [comment]
that's good to hear. I totally understand this, enjoy the summer;) - Just wanted to ask since there is no longer an update. I'm looking forward ;)
