### ISSUE TITLE
XENTORRENT TRACKER to IPS 4.2 PORT and Multi Domain Tracker

### ISSUE THREAD

**Issue by MrL0nely** [GaalexxC/IPS-4.3-BitTracker#7]
hello
is it possible to Port XENTT for XenForo 1.5 with Torrent info and data to IPS 4.2
as XENTT is abandoned by Coder and not going to update to XenForo 2.0

Also please put multi domain tracker support Like HD-Torrents and IPTorrents are using.

Thanks

**Comment by GaalexxC** [comment]
I would say its possible with the correct configuration for IPS.
This is a private tracker application, there will be no public tracker support. In other words the tracker works for your domain announce only. It can be modified for public trackers but thats a foolish request and I will not be party to that non sense.

**Comment by MrL0nely** [comment]
`This is a private tracker application, there will be no public tracker support. In other words the tracker works for your domain announce only. It can be modified for public trackers but thats a foolish request and I will not be party to that non sense.`

**i am not saying regarding PUBLIC Tracker.**

https://lookimg.com/image/0WQiA

please See this Screen-shot, these all the tracker are auto added to torrent when uploaded to IPTorrent so that if Domain is being blacklisted by ISP, it can announce to alternate one.
_All three domains are connected to same Database of IPT and are private announce only._
and are run by IPT only.
in such case if primary domain is not working, tracker will not loose the Peers and can be operated by other back-end trackers, and tracker can change domain in case of some issues and more.
**also if possible use WhatCD/OCELOT with cloud-flare integration as XBT sucks and crashes most of time and php tracker i never liked 👎 and i think multi tracker can be implemented with 3rd party tracker system, not with PHP Tracker. For huge DB and long run forum PHP Tracker is not good and it may put pressure on web server and DB**
**_Please consider it._** 
Hope You Understand my point.

Regards
Thank You.

**Comment by GaalexxC** [comment]
Developers are welcomed to extend this and add on functionality like you mentioned @MrL0nely but I am concentrating on a efficient private tracker for IPS 4x right now. Anything "additional" will come after a stable release of the original project/

Thanks
