### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by ghost** [GaalexxC/IPS-4.3-BitTracker#9]
See attached img: https://imgur.com/a/3tPmCVr

`<blockquote class="imgur-embed-pub" lang="en" data-id="a/3tPmCVr"><a href="//imgur.com/3tPmCVr"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

The app seems to work in some matter, but most of the functions don't. I am on IPS 4.3.6

My guess would be, that it does not install the DB

**Comment by GaalexxC** [comment]
Its not a complete package @HiveHoneycomb , still missing some key data elements like database as you mentioned.
- THIS IS AN INCOMPLETE VERSION UNDER DEVELOPMENT AND SHOULD NOT BE USED IN ANY ENVIRONMENT!!!

**Comment by ghost** [comment]
Ok, thank you. Do you know anything about when it is complete and usable?

**Comment by GaalexxC** [comment]
Time permitting hopefully by the end of the month I will have a Beta for testing, fingers crossed. Planning on loading into the IPS DEV MODE this weekend so I can really start getting things ready.
